### ISSUE TITLE
[Question] Can't seem to get the app running, getting "Error Execute"

### ISSUE THREAD

**Issue by keith-miller** [blueprintue/blueprintue-self-hosted-edition#105]
## Description
I can't seem to get the docker container working. I have accessed the container running the image, all of the environment variables are set, and can access the database from the container without issue. 

## Steps to reproduce this issue
1. Start the docker container with the correct env variables set
2. Load the website in the browser

## Expected behavior
App to load without issue when starting the container

## Actual behavior
I get an `Error Execute` error when loading the app in my browser.

## Additional context
Here is the error stack trace:

```
Error Execute 
#0 /opt/blueprintue-self-hosted-edition/vendor/rancoud/database/src/Database.php(257): Rancoud\Database\Database->executeStatement() 
#1 /opt/blueprintue-self-hosted-edition/vendor/rancoud/database/src/Database.php(461): Rancoud\Database\Database->select() 
#2 /opt/blueprintue-self-hosted-edition/app/models/BlueprintModel.php(69): Rancoud\Database\Database->selectAll() 
#3 /opt/blueprintue-self-hosted-edition/app/services/www/BlueprintService.php(99): app\models\BlueprintModel->getLastFive() 
#4 /opt/blueprintue-self-hosted-edition/app/controllers/www/HomeController.php(243): app\services\www\BlueprintService::getLastFive() 
#5 /opt/blueprintue-self-hosted-edition/app/controllers/www/HomeController.php(75): app\controllers\www\HomeController->getLastFiveBlueprints() 
#6 /opt/blueprintue-self-hosted-edition/vendor/rancoud/router/src/Router.php(525): app\controllers\www\HomeController->process() 
#7 /opt/blueprintue-self-hosted-edition/app/middlewares/RegisterMiddleware.php(50): Rancoud\Router\Router->handle() 
#8 /opt/blueprintue-self-hosted-edition/vendor/rancoud/router/src/Router.php(525): app\middlewares\RegisterMiddleware->process() 
#9 /opt/blueprintue-self-hosted-edition/app/middlewares/ForgotPasswordMiddleware.php(53): Rancoud\Router\Router->handle() 
#10 /opt/blueprintue-self-hosted-edition/vendor/rancoud/router/src/Router.php(525): app\middlewares\ForgotPasswordMiddleware->process() 
#11 /opt/blueprintue-self-hosted-edition/app/middlewares/LoginMiddleware.php(57): Rancoud\Router\Router->handle() 
#12 /opt/blueprintue-self-hosted-edition/vendor/rancoud/router/src/Router.php(525): app\middlewares\LoginMiddleware->process() 
#13 /opt/blueprintue-self-hosted-edition/app/middlewares/LogoutMiddleware.php(36): Rancoud\Router\Router->handle() 
#14 /opt/blueprintue-self-hosted-edition/vendor/rancoud/router/src/Router.php(525): app\middlewares\LogoutMiddleware->process() 
#15 /opt/blueprintue-self-hosted-edition/app/middlewares/SessionMiddleware.php(40): Rancoud\Router\Router->handle() 
#16 /opt/blueprintue-self-hosted-edition/vendor/rancoud/router/src/Router.php(525): app\middlewares\SessionMiddleware->process() 
#17 /opt/blueprintue-self-hosted-edition/app/middlewares/DatabaseMiddleware.php(37): Rancoud\Router\Router->handle() 
#18 /opt/blueprintue-self-hosted-edition/vendor/rancoud/router/src/Router.php(525): app\middlewares\DatabaseMiddleware->process() 
#19 /opt/blueprintue-self-hosted-edition/vendor/rancoud/router/src/Router.php(459): Rancoud\Router\Router->handle() 
#20 /opt/blueprintue-self-hosted-edition/vendor/rancoud/router/src/Router.php(529): Rancoud\Router\Router->dispatch() 
#21 /opt/blueprintue-self-hosted-edition/vendor/rancoud/router/src/Router.php(459): Rancoud\Router\Router->handle() 
#22 /opt/blueprintue-self-hosted-edition/vendor/rancoud/application/src/Application.php(242): Rancoud\Router\Router->dispatch() 
#23 /opt/blueprintue-self-hosted-edition/www/index.php(38): Rancoud\Application\Application->run() 
#24 {main} "
```

Also there doesn't seem to be any tables in the database:

```
MariaDB [blueprintue]> show tables;
Empty set (0.001 sec)
```

Any help would be great, thanks!

**Comment by keith-miller** [comment]
My bad, looks like the dump SQL script needs to run when using the Docker image as well. Sorry about that!
